### ISSUE TITLE
Unresolvable references to IExternalizable and ISerializable

### ISSUE THREAD

**Issue by lievendf** [PeterJudge-PSC/InjectABL#6]
I'm struggling to get a couple of files under the "tests" folder compiled.
S0, S1 and S3.cls have references to IExternalizable and/or ISerializable that I can't seem to locate in any existing OpenEdge pl file (using OE 11.7.5)...

**Comment by PeterJudgeZA** [comment]
I'm not sure why those S[0,1,2,3].cls files are in this project. I'll remove them and get the project building on 11.7.

**Comment by PeterJudgeZA** [comment]
The S*.cls files were removed by pull/9
